# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_utile', '0002_auto_20170708_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='article_1',
            name='publications',
            field=models.ManyToManyField(to='All_utile.Publication'),
        ),
    ]
