# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_utile', '0003_auto_20170709_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_1',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
