# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('All_utile', '0005_auto_20170709_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Tagline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogAndAuther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='All_utile.Author')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='All_utile.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeadLine', models.CharField(max_length=30)),
                ('BodyText', models.TextField()),
                ('PublishDate', models.DateTimeField(auto_now_add=True)),
                ('Authors', models.ManyToManyField(to='All_utile.Author')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='All_utile.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeadLine', models.CharField(max_length=30)),
                ('BodyText', models.TextField()),
                ('PublishDate', models.DateTimeField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='All_utile.Blog')),
            ],
        ),
    ]
