# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All_utile', '0009_auto_20170925_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='DateModel',
        ),
    ]
