# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All_utile', '0011_ckeditor_richfield_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ckeditor_richfield',
            name='Rich',
        ),
    ]
